name: Hello GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!

      - name: Show trigger info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"

  run-python:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: action/checkout@v4
      
        - name: Set up Python
          uses: action/setup-python@5
          with:
            python-version: "3.12"
        
        - name: Show Python version
          run: python --version

        - name: Run calculator
          run: python src/calculator.py
        
        - name: Install test dependencies
          run: pip install pytest

        - name: Run tests
          run: pytest tests/ -v